USE users_signature

CREATE TABLE users (
	Id				UNIQUEIDENTIFIER	NOT NULL,
	PublicKey		VARBINARY(MAX)		NOT NULL,
	PrivateKey		VARBINARY(MAX)		NOT NULL
)
GO

CREATE TABLE signatures (
	Id				UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	DocumentId		UNIQUEIDENTIFIER	NOT NULL,
	[Version]		INT					NOT NULL,
	[Hash]			VARBINARY(MAX)		NOT NULL,
	UserId			UNIQUEIDENTIFIER	NOT NULL
)
GO

SELECT *
FROM users

SELECT *
FROM signatures