version: "3.9"
services:
    user_info_api:
        build: 
            context: .
            dockerfile: UserInfoService/Dockerfile
        ports:
            - "8000:80"
            - "8001:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8001"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_Kestrel__Certificates__Default__Password: "mypass123"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
        volumes:
            - C:\Users\agats\.aspnet\https:/https/
        depends_on:
            - user_info_sql

    structure_api:
        build:
            context: .
            dockerfile: StructureService/Dockerfile
        ports:
            - "8002:80"
            - "8003:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8003"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_Kestrel__Certificates__Default__Password: "mypass123"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
        volumes:
            - C:\Users\agats\.aspnet\https:/https/
        depends_on: 
            - structure_sql

    tasks_api:
        build:
            context: .
            dockerfile: TaskCrudService/Dockerfile
        ports:
            - "8004:80"
            - "8005:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8005"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_Kestrel__Certificates__Default__Password: "mypass123"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
        volumes:
            - C:\Users\agats\.aspnet\https:/https/
        depends_on:
            - tasks_sql

    documents_api:
        build:
            context: .
            dockerfile: DocumentCrudService/Dockerfile
        ports:
            - "8006:80"
            - "8007:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8007"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_Kestrel__Certificates__Default__Password: "mypass123"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
        volumes:
            - C:\Users\agats\.aspnet\https:/https/
        depends_on:
            - documents_mongo

    company_management_api:
        build:
            context: .
            dockerfile: CompanyManagementService/Dockerfile
        ports:
            - "8008:80"
            - "8009:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8009"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_Kestrel__Certificates__Default__Password: "mypass123"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
        volumes:
            - C:\Users\agats\.aspnet\https:/https/
        depends_on:
            - company_management_redis
            - user_info_api
            - structure_api

    notification_api:
        build:
            context: .
            dockerfile: NotificationService/Dockerfile
        ports:
            - "8010:80"
            - "8011:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8011"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_Kestrel__Certificates__Default__Password: "mypass123"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
        volumes:
            - C:\Users\agats\.aspnet\https:/https/
        depends_on:
            - company_management_api
            - tasks_api

    user_info_sql:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"

    structure_sql:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"

    tasks_sql:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"

    documents_mongo:
        image: "mongo"
    
    company_management_redis:
        image: "redis"